export const productCatalogue = [
  {
    title: "Powder Canister",
    category: "beauty",
    price: 14.99,
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    warrantyInformation: "2 year warranty",
    returnPolicy: "60 days return policy",
    stockQuantity: 59,
    discountPercentage: 18.14,
    rating: 3.82,
    __v: 0,
  },
  {
    title: "Eyeshadow Palette with Mirror",
    category: "beauty",
    price: 19.99,
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    warrantyInformation: "1 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 44,
    discountPercentage: 5.5,
    rating: 3.28,
    __v: 0,
  },
  {
    title: "Essence Mascara Lash Princess",
    category: "beauty",
    price: 9.99,
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png",
    ],
    availabilityStatus: "Low Stock",
    description:
      "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    warrantyInformation: "1 month warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 5,
    discountPercentage: 7.17,
    rating: 4.94,
    __v: 0,
  },
  {
    title: "Red Lipstick",
    category: "beauty",
    price: 12.99,
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    warrantyInformation: "Lifetime warranty",
    returnPolicy: "90 days return policy",
    stockQuantity: 68,
    discountPercentage: 19.03,
    rating: 2.51,
    __v: 0,
  },
  {
    title: "Red Nail Polish",
    category: "beauty",
    price: 8.99,
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    warrantyInformation: "1 year warranty",
    returnPolicy: "No return policy",
    stockQuantity: 71,
    discountPercentage: 2.46,
    rating: 3.91,
    __v: 0,
  },
  {
    title: "Calvin Klein CK One",
    category: "fragrances",
    price: 49.99,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    warrantyInformation: "5 year warranty",
    returnPolicy: "No return policy",
    stockQuantity: 17,
    discountPercentage: 0.32,
    rating: 4.85,
    __v: 0,
  },
  {
    title: "Chanel Coco Noir Eau De",
    category: "fragrances",
    price: 129.99,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    warrantyInformation: "1 week warranty",
    returnPolicy: "60 days return policy",
    stockQuantity: 41,
    discountPercentage: 18.64,
    rating: 2.76,
    __v: 0,
  },
  {
    title: "Dior J'adore",
    category: "fragrances",
    price: 89.99,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    warrantyInformation: "Lifetime warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 91,
    discountPercentage: 17.44,
    rating: 3.31,
    __v: 0,
  },
  {
    title: "Dolce Shine Eau de",
    category: "fragrances",
    price: 69.99,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/3.png",
    ],
    availabilityStatus: "Low Stock",
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    warrantyInformation: "5 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 3,
    discountPercentage: 11.47,
    rating: 2.68,
    __v: 0,
  },
  {
    title: "Gucci Bloom Eau de",
    category: "fragrances",
    price: 79.99,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    warrantyInformation: "No warranty",
    returnPolicy: "No return policy",
    stockQuantity: 93,
    discountPercentage: 8.9,
    rating: 2.69,
    __v: 0,
  },
  {
    title: "Annibale Colombo Bed",
    category: "furniture",
    price: 1899.99,
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    warrantyInformation: "2 year warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 47,
    discountPercentage: 29,
    rating: 4.14,
    __v: 0,
  },
  {
    title: "Knoll Saarinen Executive Conference Chair",
    category: "furniture",
    price: 499.99,
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    warrantyInformation: "Lifetime warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 47,
    discountPercentage: 15.23,
    rating: 4.11,
    __v: 0,
  },
  {
    title: "Wooden Bathroom Sink With Mirror",
    category: "furniture",
    price: 799.99,
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    warrantyInformation: "6 months warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 95,
    discountPercentage: 11.22,
    rating: 3.26,
    __v: 0,
  },
  {
    title: "Annibale Colombo Sofa",
    category: "furniture",
    price: 2499.99,
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    warrantyInformation: "1 month warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 16,
    discountPercentage: 18.54,
    rating: 3.08,
    __v: 0,
  },
  {
    title: "Bedside Table African Cherry",
    category: "furniture",
    price: 299.99,
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/3.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    warrantyInformation: "6 months warranty",
    returnPolicy: "No return policy",
    stockQuantity: 16,
    discountPercentage: 9.58,
    rating: 4.48,
    __v: 0,
  },
  {
    title: "Apple",
    category: "groceries",
    price: 1.99,
    images: ["https://cdn.dummyjson.com/products/images/groceries/Apple/1.png"],
    availabilityStatus: "In Stock",
    description:
      "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
    warrantyInformation: "2 year warranty",
    returnPolicy: "60 days return policy",
    stockQuantity: 9,
    discountPercentage: 1.97,
    rating: 2.96,
    __v: 0,
  },
  {
    title: "Cat Food",
    category: "groceries",
    price: 8.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
    warrantyInformation: "3 months warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 13,
    discountPercentage: 9.57,
    rating: 2.88,
    __v: 0,
  },
  {
    title: "Beef Steak",
    category: "groceries",
    price: 12.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
    warrantyInformation: "1 month warranty",
    returnPolicy: "90 days return policy",
    stockQuantity: 96,
    discountPercentage: 17.99,
    rating: 2.83,
    __v: 0,
  },
  {
    title: "Cooking Oil",
    category: "groceries",
    price: 4.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
    warrantyInformation: "Lifetime warranty",
    returnPolicy: "60 days return policy",
    stockQuantity: 22,
    discountPercentage: 18.89,
    rating: 4.01,
    __v: 0,
  },
  {
    title: "Chicken Meat",
    category: "groceries",
    price: 9.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/2.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Fresh and tender chicken meat, suitable for various culinary preparations.",
    warrantyInformation: "Lifetime warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 69,
    discountPercentage: 10.46,
    rating: 4.61,
    __v: 0,
  },
  {
    title: "Green Bell Pepper",
    category: "groceries",
    price: 1.29,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
    warrantyInformation: "5 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 89,
    discountPercentage: 15.5,
    rating: 4.28,
    __v: 0,
  },
  {
    title: "Cucumber",
    category: "groceries",
    price: 1.49,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
    warrantyInformation: "5 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 22,
    discountPercentage: 11.44,
    rating: 4.71,
    __v: 0,
  },
  {
    title: "Dog Food",
    category: "groceries",
    price: 10.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
    warrantyInformation: "1 year warranty",
    returnPolicy: "90 days return policy",
    stockQuantity: 40,
    discountPercentage: 18.15,
    rating: 2.74,
    __v: 0,
  },
  {
    title: "Fish Steak",
    category: "groceries",
    price: 14.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Quality fish steak, suitable for grilling, baking, or pan-searing.",
    warrantyInformation: "1 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 99,
    discountPercentage: 7,
    rating: 4.83,
    __v: 0,
  },
  {
    title: "Eggs",
    category: "groceries",
    price: 2.99,
    images: ["https://cdn.dummyjson.com/products/images/groceries/Eggs/1.png"],
    availabilityStatus: "In Stock",
    description:
      "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
    warrantyInformation: "3 year warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 10,
    discountPercentage: 5.8,
    rating: 4.46,
    __v: 0,
  },
  {
    title: "Honey Jar",
    category: "groceries",
    price: 6.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
    warrantyInformation: "2 year warranty",
    returnPolicy: "90 days return policy",
    stockQuantity: 25,
    discountPercentage: 1.91,
    rating: 3.5,
    __v: 0,
  },
  {
    title: "Ice Cream",
    category: "groceries",
    price: 5.49,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/2.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/3.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/4.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
    warrantyInformation: "2 year warranty",
    returnPolicy: "No return policy",
    stockQuantity: 76,
    discountPercentage: 7.58,
    rating: 3.77,
    __v: 0,
  },
  {
    title: "Green Chili Pepper",
    category: "groceries",
    price: 0.99,
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/1.png",
    ],
    availabilityStatus: "In Stock",
    description:
      "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
    warrantyInformation: "No warranty",
    returnPolicy: "30 days return policy",
    stockQuantity: 8,
    discountPercentage: 18.51,
    rating: 4.43,
    __v: 0,
  },
  {
    title: "Juice",
    category: "groceries",
    price: 3.99,
    images: ["https://cdn.dummyjson.com/products/images/groceries/Juice/1.png"],
    availabilityStatus: "In Stock",
    description:
      "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
    warrantyInformation: "1 week warranty",
    returnPolicy: "90 days return policy",
    stockQuantity: 99,
    discountPercentage: 5.45,
    rating: 3.41,
    __v: 0,
  },
  {
    title: "Kiwi",
    category: "groceries",
    price: 2.49,
    images: ["https://cdn.dummyjson.com/products/images/groceries/Kiwi/1.png"],
    availabilityStatus: "Low Stock",
    description:
      "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
    warrantyInformation: "6 months warranty",
    returnPolicy: "7 days return policy",
    stockQuantity: 1,
    discountPercentage: 10.32,
    rating: 4.37,
    __v: 0,
  },
];
